### ISSUE TITLE
Ploting error

### ISSUE THREAD

**Issue by gHARD1** [alopezrivera/huracan#3]
Hello,

I encountered an issue while trying to use the `plot_cycle_graph` function in the `engine.py` file. The error message is as follows:
TypeError: scatter.init() got an unexpected keyword argument 'x_label'

The error occurs at line 864 in `engine.py`:

It seems that the scatter function does not accept x_label as a keyword argument. This is causing the plot_cycle_graph function to fail.

Could you please look into this issue and provide a fix or guidance on how to resolve it?

Thank you

**Comment by alopezrivera** [comment]
Hi, I've just published a pre-release addressing this error. I'd appreciate if you could test it out and confirm it works on your side.

Thanks in advance! :)

https://github.com/alopezrivera/huracan/releases/tag/0.1.alpha

**Comment by gHARD1** [comment]
Hi, its now working for me, but in the requirements file mpl plotter version is "55.5.0", i change it to 5.5.0 and works.

Thank you so much

**Comment by gHARD1** [comment]
Just tried to run Turbojet example and the following error appears: TypeError: scatter.__init__() got an unexpected keyword argument 'y_tick_ndecimals'

**Comment by alopezrivera** [comment]
What version of `mpl_plotter` are you on? It could be that it's outdated. Could you update your version of `mpl_plotter` to 5.5.0 and try again?

```
python -m pip install --upgrade mpl_plotter
```

**Comment by alopezrivera** [comment]
Will look into it

**Comment by alopezrivera** [comment]
Fixed! I've run all examples and I believe everything now runs as it should :)

**Comment by gHARD1** [comment]
Its now running perfectly,

Thanks

**Comment by gHARD1** [comment]
Its now running perfectly,

Thanks
